### ISSUE TITLE
AWS Cloud config - static field in networks

### ISSUE THREAD

**Issue by bijukunjummen** [enaml-ops/omg-cli#12]
Accounting for `static` field in networks section - 

```
networks:
- name: private
  type: manual
  subnets:
  - range: 10.10.0.0/24
    gateway: 10.10.0.1
    az: z1
    static: [10.10.0.62]
    dns: [10.10.0.2]
    cloud_properties: {subnet: subnet-f2744a86}
  - range: 10.10.64.0/24
    gateway: 10.10.64.1
    az: z2
    static: [10.10.64.121, 10.10.64.122]
    dns: [10.10.0.2]
    cloud_properties: {subnet: subnet-eb8bd3ad}
```
