### ISSUE TITLE
AWS cloud config plugin fails to create > 2 subnets

### ISSUE THREAD

**Issue by zmb3** [enaml-ops/omg-cli#39]
This example is before @calebwashburn's recent refactor.  I have yet to figure out the flag changes to try and reproduce on 1.x.

Try to create 3 subnets:
```
omg-cli deploy-cloudconfig \
--bosh-url https://x.x.x.x \
--bosh-port 25555 \
--bosh-user director \
--bosh-pass `cat directorpwd` \
--ssl-ignore \
--print-manifest \
cloudconfig-plugin-linux \
--aws-region us-east-1 \
--aws-security-group PCF-Sec-Group \
--aws-az-name-1 us-east-1a \
--aws-az-name-2 us-east-1b \
--dns-1 x.x.x.x \
--cidr-1 x.x.x.x/x \
--gateway-1 x.x.x.x \
--bosh-az-name-1 az1a \
--aws-subnet-name-1 subnet-1 \
--bosh-reserve-range-1 "x.x.x.x-x.x.x.x" \
--bosh-static-range-1 "x.x.x.x-x.x.x.x" \
--dns-2 x.x.x.x \
--cidr-2 x.x.x.x/x \
--gateway-2 x.x.x.x \
--bosh-az-name-2 az1b \
--aws-subnet-name-2 subnet-2 \
--bosh-reserve-range-2 "x.x.x.x-x.x.x.x" \
--bosh-static-range-2 "x.x.x.x-x.x.x.x" \
--dns-3 x.x.x.x \
--cidr-3 x.x.x.x/x \
--gateway-3 x.x.x.x \
--bosh-az-name-3 az2a \
--aws-subnet-name-3 subnet-3 \
--bosh-reserve-range-3 "x.x.x.x-x.x.x.x" \
--bosh-static-range-3 "x.x.x.x-x.x.x.x"
```

Produces a cloud config with only 2 subnets:
```
azs:
- name: az1a
  cloud_properties:
    availability_zone: us-east-1a
    security_groups:
    - PCF-Sec-Group
- name: az1b
  cloud_properties:
    availability_zone: us-east-1b
    security_groups:
    - PCF-Sec-Group
networks:
- name: private
  type: manual
  subnets:
  - range: x.x.x.x/x
    gateway: x.x.x.x
    dns:
    - x.x.x.x
    reserved:
    - x.x.x.x-x.x.x.x
    static:
    - x.x.x.x-x.x.x.x
    az: az1a
    cloud_properties:
      subnet: subnet-1
  - range: x.x.x.x/x
    gateway: x.x.x.x
    dns:
    - x.x.x.x
    reserved:
    - x.x.x.x-x.x.x.x
    static:
    - x.x.x.x-x.x.x.x
    az: az1b
    cloud_properties:
      subnet: subnet-2
- name: vip
  type: vip
```
