### ISSUE TITLE
Manifest error when deploying bosh director on GCP

### ISSUE THREAD

**Issue by jtgammon** [enaml-ops/omg-cli#56]
I am seeing the following error when I try to deploy the bosh director to GCP on omg version v1.0.7-628bb0.

```
omg gcp --mode uaa --gcp-network-name pcf --gcp-subnetwork-name bosh --gcp-project fe-jgammon --gcp-machine-type g1-small --gcp-default-zone us-central1-a --gateway 10.0.0.1 --dns 8.8.8.8 --cidr 10.0.0.0/24 --bosh-private-ip 10.0.0.10 

Deployment manifest: '/home/jgammon/omg/omg-bosh.349171'
Deployment state: '/home/jgammon/omg/omg-bosh-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:04)
  Downloading release 'uaa'... Skipped [Found in local cache] (00:00:00)
  Validating release 'uaa'... Finished (00:00:08)
  Downloading release 'bosh-google-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-google-cpi'... Finished (00:00:07)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Failed (00:00:00)
Failed validating (00:00:20)

Command 'deploy' failed:
  Validating deployment manifest:
    only one network can be the default for 'dns'
    only one network can be the default for 'gateway'
```

I looked at the manifest, and I'm pretty sure the issue is here where it lists the private network twice.

```
  resource_pool: vms
  instances: 1
  networks:
  - name: private
    static_ips:
    - 10.0.0.10
    default:
    - dns
    - gateway
  - name: private
    static_ips:
    - 10.0.0.10
    default:
    - dns
    - gateway
cloud_provider:
```
