### ISSUE TITLE
Add Flag to support trusted certs in bosh.

### ISSUE THREAD

**Issue by haydonryan** [enaml-ops/omg-cli#6]
Gemfire tile requires the director to have a trusted cert inserted by bosh.

```
director:
      address: 127.0.0.1
      name: bosh
      db: *db
      cpi_job: cpi
      enable_snapshots: false
      trusted_certs: |
        -----BEGIN CERTIFICATE-----
```
